tabela_pha_tabelaPha:
    resource: "@tabelaPhaBundle/Resources/config/routing/tabela.yml"
    prefix:   /tabelaPha

tabela_pha_homepage:
    path:     /tabelaPha/{letra}
    defaults: { _controller: tabelaPhaBundle:Tabela:index, letra: 'A' }


tabela_pha:
    path:     /Pha
    defaults: { _controller: tabelaPhaBundle:Tabela:search }
