<?php

namespace tabelaPhaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TabelaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TabelaRepository extends EntityRepository
{
    public function findByLetra($letra)
    {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder();
        $queryBuilder->select('t')
            ->from('tabelaPhaBundle\Entity\Tabela', 't')
            ->where($queryBuilder->expr()->like('t.phaName', ':letra'))
            ->setParameter('letra', $letra.'%');

        $query = $queryBuilder->getQuery();

        return $query->getResult();
    }
}
