<?php

namespace tabelaPhaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TabelaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TabelaRepository extends EntityRepository
{
}
